### ISSUE TITLE
Question about P2~P4 data

### ISSUE THREAD

**Issue by hongnianwang** [yoshall/UrbanFM#2]
Very good job, 

when are you post the rest of the data?  It will be very helpful to me, thank you

Regards,

**Comment by yoshall** [comment]
Hi Hongnian, since our paper has already been accepted by a conference, we will release the rest of the data after the camera-ready version. Hope the data would help you soon.

**Comment by hongnianwang** [comment]
got it, thanks

**Comment by veronicasr9** [comment]
Hi @yoshall ,

Could you please upload the rest dataset if it's convenient?  It will help me a lot :)

Thanks and Regards.

**Comment by yoshall** [comment]
Sorry for the late response. The data of P1 to P4 are released at ./data folder. Please feel free to use them.

**Comment by yoshall** [comment]
Sorry for the late response. The data of P1 to P4 are released at ./data folder. Please feel free to use them.
