### ISSUE TITLE
Question about P1  dateset

### ISSUE THREAD

**Issue by lilipanpan** [yoshall/UrbanFM#3]
Your work is very helpful to us,I would like to know more about P1 dataset,for example, the area of the entire dataset area and the unit of pedestrian flow ?

**Comment by yoshall** [comment]
Hi, thanks for your interest in this work. The MBR is mbr_bj = MBR(39.8200, 116.2498, 39.9966, 116.4950). The unit is with around 150m*150m in fine-grained level and 600m*600m in coarse-grained level.
